name: Specter Docker Action
description: An example for Docker GitHub Action

inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World

outputs:
  training_center:
    description: The training center

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}