name: Run Reusable Workflow

on:
    workflow_dispatch:
        inputs:
            who-to-greet:
                description: Who to greet
                required: true
                type: string

jobs:
    test:
        uses: Bumeranghc/GitHubDockerAction/.github/workflows/reusable-workflow.yaml@main
        with:
            who-to-greet: ${{ inputs.who-to-greet }}
